import { Student } from '../types/student';
import { Establishment } from '../types/establishment';
import { Template } from '../types/template';

export const SAMPLE_STUDENTS: Student[] = [
  {
    id: 'std-1',
    nom: 'KOUAMÉ',
    prenom: 'Jean-Baptiste',
    nom_complet: 'Jean-Baptiste KOUAMÉ',
    email: 'j.kouame@example.com',
    matricule: 'CERT-2026-001',
    formation: 'Développement Web & Intelligence Artificielle',
    specialite: 'Architecte Logiciel',
    note: '18.5',
    moyenne: '18.5/20',
    mention: 'Très Bien avec Félicitations',
    rang: '1er / 48',
    duree: '600 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '15 Juin 2026',
    numero_attestation: 'ATT-2026-001',
    isValid: true,
  },
  {
    id: 'std-2',
    nom: 'BERNARD',
    prenom: 'Sophie',
    nom_complet: 'Sophie BERNARD',
    email: 's.bernard@example.com',
    matricule: 'CERT-2026-002',
    formation: 'Développement Web & Intelligence Artificielle',
    specialite: 'Data Science & IA',
    note: '17.2',
    moyenne: '17.2/20',
    mention: 'Très Bien',
    rang: '2ème / 48',
    duree: '600 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '15 Juin 2026',
    numero_attestation: 'ATT-2026-002',
    isValid: true,
  },
  {
    id: 'std-3',
    nom: 'DIOP',
    prenom: 'Mamadou',
    nom_complet: 'Mamadou DIOP',
    email: 'm.diop@example.com',
    matricule: 'CERT-2026-003',
    formation: 'Cybersécurité & Cloud Computing',
    specialite: 'Sécurité Réseaux',
    note: '16.0',
    moyenne: '16.0/20',
    mention: 'Bien',
    rang: '5ème / 35',
    duree: '500 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '20 Juin 2026',
    numero_attestation: 'ATT-2026-003',
    isValid: true,
  },
  {
    id: 'std-4',
    nom: 'LEFEBVRE',
    prenom: 'Camille',
    nom_complet: 'Camille LEFEBVRE',
    email: 'c.lefebvre@example.com',
    matricule: 'CERT-2026-004',
    formation: 'Management des Projets Digitaux',
    specialite: 'Agile & Product Management',
    note: '15.8',
    moyenne: '15.8/20',
    mention: 'Bien',
    rang: '3ème / 30',
    duree: '400 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '10 Juillet 2026',
    numero_attestation: 'ATT-2026-004',
    isValid: true,
  },
  {
    id: 'std-5',
    nom: 'BENALI',
    prenom: 'Youssef',
    nom_complet: 'Youssef BENALI',
    email: 'y.benali@example.com',
    matricule: 'CERT-2026-005',
    formation: 'UX/UI Design & Product Design',
    specialite: 'Design System & Ergonomie',
    note: '19.0',
    moyenne: '19.0/20',
    mention: 'Très Bien avec Majoration',
    rang: '1er / 25',
    duree: '450 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '12 Juillet 2026',
    numero_attestation: 'ATT-2026-005',
    isValid: true,
  },
  {
    id: 'std-6',
    nom: 'NGUYEN',
    prenom: 'Linh',
    nom_complet: 'Linh NGUYEN',
    email: 'l.nguyen@example.com',
    matricule: 'CERT-2026-006',
    formation: 'Développement Web & Intelligence Artificielle',
    specialite: 'DevOps & CI/CD',
    note: '14.5',
    moyenne: '14.5/20',
    mention: 'Assez Bien',
    rang: '12ème / 48',
    duree: '600 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '15 Juin 2026',
    numero_attestation: 'ATT-2026-006',
    isValid: true,
  },
  {
    id: 'std-7',
    nom: 'GARCIA',
    prenom: 'Mateo',
    nom_complet: 'Mateo GARCIA',
    email: 'm.garcia@example.com',
    matricule: 'CERT-2026-007',
    formation: 'Cybersécurité & Cloud Computing',
    specialite: 'Cloud Architecture AWS',
    note: '16.7',
    moyenne: '16.7/20',
    mention: 'Très Bien',
    rang: '3ème / 35',
    duree: '500 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '20 Juin 2026',
    numero_attestation: 'ATT-2026-007',
    isValid: true,
  },
  {
    id: 'std-8',
    nom: 'MOREAU',
    prenom: 'Claire',
    nom_complet: 'Claire MOREAU',
    email: 'c.moreau@example.com',
    matricule: 'CERT-2026-008',
    formation: 'Management des Projets Digitaux',
    specialite: 'Scrum Master',
    note: '14.0',
    moyenne: '14.0/20',
    mention: 'Assez Bien',
    rang: '10ème / 30',
    duree: '400 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '10 Juillet 2026',
    numero_attestation: 'ATT-2026-008',
    isValid: true,
  },
  {
    id: 'std-9',
    nom: 'TRAORÉ',
    prenom: 'Aminata',
    nom_complet: 'Aminata TRAORÉ',
    email: 'a.traore@example.com',
    matricule: 'CERT-2026-009',
    formation: 'UX/UI Design & Product Design',
    specialite: 'User Research',
    note: '17.8',
    moyenne: '17.8/20',
    mention: 'Très Bien',
    rang: '2ème / 25',
    duree: '450 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '12 Juillet 2026',
    numero_attestation: 'ATT-2026-009',
    isValid: true,
  },
  {
    id: 'std-10',
    nom: 'DUBOIS',
    prenom: 'Antoine',
    nom_complet: 'Antoine DUBOIS',
    email: 'a.dubois@example.com',
    matricule: 'CERT-2026-010',
    formation: 'Développement Web & Intelligence Artificielle',
    specialite: 'Fullstack React & Rust',
    note: '18.2',
    moyenne: '18.2/20',
    mention: 'Très Bien',
    rang: '3ème / 48',
    duree: '600 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '15 Juin 2026',
    numero_attestation: 'ATT-2026-010',
    isValid: true,
  }
];

export const DEFAULT_ESTABLISHMENT: Establishment = {
  name: 'Institut Supérieur des Hautes Études & Technologies',
  address: '145 Avenue de la République, 75011 Paris',
  phone: '+33 (0)1 48 00 22 44',
  email: 'contact@ishet-formation.fr',
  website: 'www.ishet-formation.fr',
  slogan: 'Excellence Pédagogique & Innovation Numérique',
  directorName: 'Prof. Alexandre DE VANCE',
  signatures: [
    {
      id: 'sig-1',
      title: 'Le Directeur de l\'Établissement',
      signatoryName: 'Prof. Alexandre DE VANCE',
    },
    {
      id: 'sig-2',
      title: 'La Responsable Pédagogique',
      signatoryName: 'Dr. Hélène ROUSSEAU',
    }
  ]
};

export const DEFAULT_TEMPLATES: Template[] = [
  {
    id: 'tmpl-excellence-gold',
    name: 'Attestation Classique Or & Marine',
    description: 'Design académique prestigieux avec filigrane doré et typographie élégante',
    category: 'attestation',
    pageSize: 'A4',
    orientation: 'landscape',
    dimensions: { width: 1123, height: 794 },
    themeColor: '#4f46e5',
    isDefault: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    elements: [
      // Border frame
      {
        id: 'el-border',
        type: 'rectangle',
        x: 30,
        y: 30,
        width: 1063,
        height: 734,
        backgroundColor: 'transparent',
        borderColor: '#4338ca',
        borderWidth: 4,
        isLocked: true
      },
      {
        id: 'el-inner-border',
        type: 'rectangle',
        x: 40,
        y: 40,
        width: 1043,
        height: 714,
        backgroundColor: 'transparent',
        borderColor: '#d97706',
        borderWidth: 1,
        isLocked: true
      },
      // Header Title
      {
        id: 'el-establishment-header',
        type: 'text',
        x: 561,
        y: 80,
        width: 900,
        height: 40,
        content: 'INSTITUT SUPÉRIEUR DES HAUTES ÉTUDES & TECHNOLOGIES',
        fontFamily: 'Cinzel',
        fontSize: 22,
        fontWeight: 'bold',
        color: '#1e1b4b',
        textAlign: 'center'
      },
      {
        id: 'el-subtitle',
        type: 'text',
        x: 561,
        y: 115,
        width: 900,
        height: 30,
        content: 'ÉTABLISSEMENT D\'ENSEIGNEMENT SUPÉRIEUR DE RENOMMÉE',
        fontFamily: 'Inter',
        fontSize: 11,
        fontWeight: '500',
        color: '#d97706',
        textAlign: 'center'
      },
      // Document Title
      {
        id: 'el-doc-title',
        type: 'text',
        x: 561,
        y: 180,
        width: 800,
        height: 60,
        content: 'ATTESTATION DE RÉUSSITE',
        fontFamily: 'Outfit',
        fontSize: 36,
        fontWeight: 'bold',
        color: '#4338ca',
        textAlign: 'center'
      },
      // Separator line
      {
        id: 'el-line-1',
        type: 'line',
        x: 361,
        y: 245,
        width: 400,
        height: 2,
        backgroundColor: '#d97706',
      },
      // Main Body Paragraph
      {
        id: 'el-body-prefix',
        type: 'text',
        x: 561,
        y: 280,
        width: 900,
        height: 30,
        content: 'Le Conseil d\'Évaluation et le Directeur attestent que :',
        fontFamily: 'Playfair Display',
        fontSize: 16,
        fontStyle: 'italic',
        color: '#475569',
        textAlign: 'center'
      },
      // Student Name Variable
      {
        id: 'el-student-name',
        type: 'variable',
        variableName: '{{nom_complet}}',
        x: 561,
        y: 330,
        width: 900,
        height: 55,
        content: '{{nom_complet}}',
        fontFamily: 'Outfit',
        fontSize: 34,
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'center'
      },
      // Body Text
      {
        id: 'el-body-text',
        type: 'text',
        x: 561,
        y: 400,
        width: 880,
        height: 80,
        content: 'a suivi avec succès la formation professionnelle certifiante en\n{{formation}}\net a satisfait à l\'ensemble des épreuves de contrôle des connaissances.',
        fontFamily: 'Inter',
        fontSize: 16,
        color: '#334155',
        textAlign: 'center'
      },
      // Details Grid (Mention & Note)
      {
        id: 'el-mention-note',
        type: 'text',
        x: 561,
        y: 495,
        width: 800,
        height: 40,
        content: 'Mention : {{mention}}   |   Moyenne : {{moyenne}}   |   Rang : {{rang}}',
        fontFamily: 'Inter',
        fontSize: 15,
        fontWeight: '600',
        color: '#1e1b4b',
        textAlign: 'center'
      },
      // Date and Place
      {
        id: 'el-date-place',
        type: 'text',
        x: 561,
        y: 560,
        width: 700,
        height: 30,
        content: 'Délivré à Paris, le {{date_obtention}}',
        fontFamily: 'Playfair Display',
        fontSize: 14,
        fontStyle: 'italic',
        color: '#64748b',
        textAlign: 'center'
      },
      // Numbering Footer
      {
        id: 'el-numbering',
        type: 'text',
        x: 100,
        y: 715,
        width: 300,
        height: 25,
        content: 'N° d\'enregistrement : {{numero}}',
        fontFamily: 'Inter',
        fontSize: 10,
        color: '#94a3b8',
        textAlign: 'left'
      },
      // Signatures Labels
      {
        id: 'el-sig-left-title',
        type: 'text',
        x: 230,
        y: 620,
        width: 300,
        height: 25,
        content: 'La Responsable Pédagogique',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: '600',
        color: '#334155',
        textAlign: 'center'
      },
      {
        id: 'el-sig-left-name',
        type: 'text',
        x: 230,
        y: 690,
        width: 300,
        height: 25,
        content: 'Dr. Hélène ROUSSEAU',
        fontFamily: 'Playfair Display',
        fontSize: 13,
        color: '#475569',
        textAlign: 'center'
      },
      {
        id: 'el-sig-right-title',
        type: 'text',
        x: 890,
        y: 620,
        width: 300,
        height: 25,
        content: 'Le Directeur de l\'Établissement',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: '600',
        color: '#334155',
        textAlign: 'center'
      },
      {
        id: 'el-sig-right-name',
        type: 'text',
        x: 890,
        y: 690,
        width: 300,
        height: 25,
        content: 'Prof. Alexandre DE VANCE',
        fontFamily: 'Playfair Display',
        fontSize: 13,
        color: '#475569',
        textAlign: 'center'
      }
    ]
  },
  {
    id: 'tmpl-modern-tech',
    name: 'Certificat Moderne Épuré',
    description: 'Style contemporain minimaliste avec des aplats de couleur cyan/indigo et design épuré',
    category: 'certificat',
    pageSize: 'A4',
    orientation: 'landscape',
    dimensions: { width: 1123, height: 794 },
    themeColor: '#0284c7',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    elements: [
      {
        id: 'el-bg-bar',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 25,
        height: 794,
        backgroundColor: '#0284c7',
        isLocked: true
      },
      {
        id: 'el-header-title',
        type: 'text',
        x: 570,
        y: 90,
        width: 800,
        height: 50,
        content: 'CERTIFICAT ACADÉMIQUE',
        fontFamily: 'Outfit',
        fontSize: 38,
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'center'
      },
      {
        id: 'el-sub-header',
        type: 'text',
        x: 570,
        y: 150,
        width: 800,
        height: 30,
        content: 'DÉCERNÉ PAR L\'INSTITUT SUPÉRIEUR DES HAUTES ÉTUDES',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: '600',
        color: '#0284c7',
        textAlign: 'center'
      },
      {
        id: 'el-cert-text-1',
        type: 'text',
        x: 570,
        y: 250,
        width: 800,
        height: 30,
        content: 'Ce certificat valide que',
        fontFamily: 'Inter',
        fontSize: 16,
        color: '#64748b',
        textAlign: 'center'
      },
      {
        id: 'el-name',
        type: 'variable',
        variableName: '{{nom_complet}}',
        x: 570,
        y: 300,
        width: 800,
        height: 50,
        content: '{{nom_complet}}',
        fontFamily: 'Outfit',
        fontSize: 32,
        fontWeight: 'bold',
        color: '#0369a1',
        textAlign: 'center'
      },
      {
        id: 'el-desc',
        type: 'text',
        x: 570,
        y: 380,
        width: 820,
        height: 70,
        content: 'a validé l\'intégralité des compétences exigées pour le programme\n{{formation}}\n(Spécialité : {{specialite}})',
        fontFamily: 'Inter',
        fontSize: 16,
        color: '#334155',
        textAlign: 'center'
      },
      {
        id: 'el-meta',
        type: 'text',
        x: 570,
        y: 480,
        width: 800,
        height: 30,
        content: 'Session {{annee_academique}} • Durée : {{duree}} • Mention : {{mention}}',
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: '500',
        color: '#475569',
        textAlign: 'center'
      },
      {
        id: 'el-date',
        type: 'text',
        x: 570,
        y: 570,
        width: 600,
        height: 30,
        content: 'Fait le {{date_obtention}}',
        fontFamily: 'Inter',
        fontSize: 13,
        color: '#94a3b8',
        textAlign: 'center'
      },
      {
        id: 'el-sig-director',
        type: 'text',
        x: 850,
        y: 650,
        width: 300,
        height: 30,
        content: 'Le Directeur Pédagogique\nProf. Alexandre DE VANCE',
        fontFamily: 'Inter',
        fontSize: 12,
        color: '#334155',
        textAlign: 'center'
      }
    ]
  }
];
