import { Student } from '../types/student';
import { Establishment } from '../types/establishment';
import { Template } from '../types/template';

export const SAMPLE_STUDENTS: Student[] = [
  {
    id: 'std-1',
    nom: 'KOUAMÉ',
    prenom: 'Jean-Baptiste',
    nom_complet: 'Jean-Baptiste KOUAMÉ',
    email: 'j.kouame@example.com',
    matricule: 'CERT-2026-001',
    formation: 'Développement Web & Intelligence Artificielle',
    specialite: 'Architecte Logiciel',
    note: '18.5',
    moyenne: '18.5/20',
    mention: 'Très Bien avec Félicitations',
    rang: '1er / 48',
    duree: '600 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '15 Juin 2026',
    numero_attestation: 'ATT-2026-001',
    isValid: true,
  },
  {
    id: 'std-2',
    nom: 'BERNARD',
    prenom: 'Sophie',
    nom_complet: 'Sophie BERNARD',
    email: 's.bernard@example.com',
    matricule: 'CERT-2026-002',
    formation: 'Développement Web & Intelligence Artificielle',
    specialite: 'Data Science & IA',
    note: '17.2',
    moyenne: '17.2/20',
    mention: 'Très Bien',
    rang: '2ème / 48',
    duree: '600 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '15 Juin 2026',
    numero_attestation: 'ATT-2026-002',
    isValid: true,
  },
  {
    id: 'std-3',
    nom: 'DIOP',
    prenom: 'Mamadou',
    nom_complet: 'Mamadou DIOP',
    email: 'm.diop@example.com',
    matricule: 'CERT-2026-003',
    formation: 'Cybersécurité & Cloud Computing',
    specialite: 'Sécurité Réseaux',
    note: '16.0',
    moyenne: '16.0/20',
    mention: 'Bien',
    rang: '5ème / 35',
    duree: '500 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '20 Juin 2026',
    numero_attestation: 'ATT-2026-003',
    isValid: true,
  },
  {
    id: 'std-4',
    nom: 'LEFEBVRE',
    prenom: 'Camille',
    nom_complet: 'Camille LEFEBVRE',
    email: 'c.lefebvre@example.com',
    matricule: 'CERT-2026-004',
    formation: 'Management des Projets Digitaux',
    specialite: 'Agile & Product Management',
    note: '15.8',
    moyenne: '15.8/20',
    mention: 'Bien',
    rang: '3ème / 30',
    duree: '400 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '10 Juillet 2026',
    numero_attestation: 'ATT-2026-004',
    isValid: true,
  },
  {
    id: 'std-5',
    nom: 'BENALI',
    prenom: 'Youssef',
    nom_complet: 'Youssef BENALI',
    email: 'y.benali@example.com',
    matricule: 'CERT-2026-005',
    formation: 'UX/UI Design & Product Design',
    specialite: 'Design System & Ergonomie',
    note: '19.0',
    moyenne: '19.0/20',
    mention: 'Très Bien avec Majoration',
    rang: '1er / 25',
    duree: '450 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '12 Juillet 2026',
    numero_attestation: 'ATT-2026-005',
    isValid: true,
  },
  {
    id: 'std-6',
    nom: 'NGUYEN',
    prenom: 'Linh',
    nom_complet: 'Linh NGUYEN',
    email: 'l.nguyen@example.com',
    matricule: 'CERT-2026-006',
    formation: 'Développement Web & Intelligence Artificielle',
    specialite: 'DevOps & CI/CD',
    note: '14.5',
    moyenne: '14.5/20',
    mention: 'Assez Bien',
    rang: '12ème / 48',
    duree: '600 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '15 Juin 2026',
    numero_attestation: 'ATT-2026-006',
    isValid: true,
  },
  {
    id: 'std-7',
    nom: 'GARCIA',
    prenom: 'Mateo',
    nom_complet: 'Mateo GARCIA',
    email: 'm.garcia@example.com',
    matricule: 'CERT-2026-007',
    formation: 'Cybersécurité & Cloud Computing',
    specialite: 'Cloud Architecture AWS',
    note: '16.7',
    moyenne: '16.7/20',
    mention: 'Très Bien',
    rang: '3ème / 35',
    duree: '500 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '20 Juin 2026',
    numero_attestation: 'ATT-2026-007',
    isValid: true,
  },
  {
    id: 'std-8',
    nom: 'MOREAU',
    prenom: 'Claire',
    nom_complet: 'Claire MOREAU',
    email: 'c.moreau@example.com',
    matricule: 'CERT-2026-008',
    formation: 'Management des Projets Digitaux',
    specialite: 'Scrum Master',
    note: '14.0',
    moyenne: '14.0/20',
    mention: 'Assez Bien',
    rang: '10ème / 30',
    duree: '400 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '10 Juillet 2026',
    numero_attestation: 'ATT-2026-008',
    isValid: true,
  },
  {
    id: 'std-9',
    nom: 'TRAORÉ',
    prenom: 'Aminata',
    nom_complet: 'Aminata TRAORÉ',
    email: 'a.traore@example.com',
    matricule: 'CERT-2026-009',
    formation: 'UX/UI Design & Product Design',
    specialite: 'User Research',
    note: '17.8',
    moyenne: '17.8/20',
    mention: 'Très Bien',
    rang: '2ème / 25',
    duree: '450 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '12 Juillet 2026',
    numero_attestation: 'ATT-2026-009',
    isValid: true,
  },
  {
    id: 'std-10',
    nom: 'DUBOIS',
    prenom: 'Antoine',
    nom_complet: 'Antoine DUBOIS',
    email: 'a.dubois@example.com',
    matricule: 'CERT-2026-010',
    formation: 'Développement Web & Intelligence Artificielle',
    specialite: 'Fullstack React & Rust',
    note: '18.2',
    moyenne: '18.2/20',
    mention: 'Très Bien',
    rang: '3ème / 48',
    duree: '600 heures',
    annee: '2026',
    annee_academique: '2025-2026',
    date_obtention: '15 Juin 2026',
    numero_attestation: 'ATT-2026-010',
    isValid: true,
  }
];

export const DEFAULT_ESTABLISHMENT: Establishment = {
  name: 'INSTITUT SUPÉRIEUR DES HAUTES ÉTUDES & TECHNOLOGIES',
  address: '145 Avenue de la République, 75011 Paris',
  phone: '+33 (0)1 48 00 22 44',
  email: 'contact@ishet-formation.fr',
  website: 'www.ishet-formation.fr',
  slogan: 'Excellence Pédagogique & Innovation Numérique',
  directorName: 'Prof. Alexandre DE VANCE',
  signatures: [
    {
      id: 'sig-1',
      title: 'Le Directeur de l\'Établissement',
      signatoryName: 'Prof. Alexandre DE VANCE',
    },
    {
      id: 'sig-2',
      title: 'La Responsable Pédagogique',
      signatoryName: 'Dr. Hélène ROUSSEAU',
    }
  ]
};

export const DEFAULT_TEMPLATES: Template[] = [
  {
    id: 'tmpl-excellence-gold',
    name: 'Attestation Prestige Or & Marine',
    description: 'Design académique royal parfaitement centré avec triple cadre or/marine et ornements luxueux',
    category: 'attestation',
    pageSize: 'A4',
    orientation: 'landscape',
    dimensions: { width: 1123, height: 794 },
    themeColor: '#4f46e5',
    isDefault: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    elements: [
      // Outer Thick Gold Border
      {
        id: 'el-border-outer',
        type: 'rectangle',
        x: 25,
        y: 25,
        width: 1073,
        height: 744,
        backgroundColor: 'transparent',
        borderColor: '#d97706',
        borderWidth: 4,
        isLocked: true
      },
      // Middle Navy Border
      {
        id: 'el-border-mid',
        type: 'rectangle',
        x: 35,
        y: 35,
        width: 1053,
        height: 724,
        backgroundColor: 'transparent',
        borderColor: '#1e1b4b',
        borderWidth: 2,
        isLocked: true
      },
      // Inner Fine Gold Border
      {
        id: 'el-border-inner',
        type: 'rectangle',
        x: 42,
        y: 42,
        width: 1039,
        height: 710,
        backgroundColor: 'transparent',
        borderColor: '#f59e0b',
        borderWidth: 1,
        isLocked: true
      },

      // Top Emblem Ornament
      {
        id: 'el-top-ornament',
        type: 'text',
        x: 561.5,
        y: 65,
        width: 800,
        height: 30,
        content: '✦  🎓  REPUBLIQUE FRANÇAISE  🎓  ✦',
        fontFamily: 'Outfit',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#d97706',
        textAlign: 'center'
      },

      // Header Establishment Name (Centered at 561.5)
      {
        id: 'el-establishment-header',
        type: 'text',
        x: 561.5,
        y: 95,
        width: 950,
        height: 40,
        content: 'INSTITUT SUPÉRIEUR DES HAUTES ÉTUDES & TECHNOLOGIES',
        fontFamily: 'Cinzel',
        fontSize: 22,
        fontWeight: 'bold',
        color: '#1e1b4b',
        textAlign: 'center'
      },

      // Subtitle
      {
        id: 'el-subtitle',
        type: 'text',
        x: 561.5,
        y: 135,
        width: 900,
        height: 25,
        content: 'ÉTABLISSEMENT D\'ENSEIGNEMENT SUPÉRIEUR DE RENOMMÉE ACADÉMIQUE',
        fontFamily: 'Inter',
        fontSize: 10,
        fontWeight: '600',
        color: '#d97706',
        textAlign: 'center'
      },

      // Document Title
      {
        id: 'el-doc-title',
        type: 'text',
        x: 561.5,
        y: 190,
        width: 850,
        height: 60,
        content: 'ATTESTATION DE RÉUSSITE',
        fontFamily: 'Outfit',
        fontSize: 38,
        fontWeight: 'bold',
        color: '#4338ca',
        textAlign: 'center'
      },

      // Gold Separator Banner
      {
        id: 'el-gold-banner',
        type: 'text',
        x: 561.5,
        y: 240,
        width: 500,
        height: 25,
        content: '✦   ───────   ⚜   ───────   ✦',
        fontFamily: 'Inter',
        fontSize: 14,
        color: '#d97706',
        textAlign: 'center'
      },

      // Body Intro Sentence
      {
        id: 'el-body-prefix',
        type: 'text',
        x: 561.5,
        y: 280,
        width: 900,
        height: 30,
        content: 'Le Conseil d\'Évaluation et la Direction Académique attestent que :',
        fontFamily: 'Playfair Display',
        fontSize: 16,
        fontStyle: 'italic',
        color: '#475569',
        textAlign: 'center'
      },

      // Student Full Name (Centered & Highlighted in 36pt Bold)
      {
        id: 'el-student-name',
        type: 'variable',
        variableName: '{{nom_complet}}',
        x: 561.5,
        y: 330,
        width: 950,
        height: 55,
        content: '{{nom_complet}}',
        fontFamily: 'Outfit',
        fontSize: 36,
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'center'
      },

      // Main Paragraph Text
      {
        id: 'el-body-text',
        type: 'text',
        x: 561.5,
        y: 405,
        width: 900,
        height: 80,
        content: 'a suivi avec succès la formation professionnelle certifiante en\n{{formation}}\net a satisfait avec distinction à l\'ensemble des épreuves de contrôle des connaissances.',
        fontFamily: 'Inter',
        fontSize: 16,
        color: '#334155',
        textAlign: 'center'
      },

      // Details Pill Bar (Mention & Moyenne)
      {
        id: 'el-mention-note',
        type: 'text',
        x: 561.5,
        y: 495,
        width: 850,
        height: 35,
        content: 'Mention : {{mention}}    •    Moyenne : {{moyenne}}    •    Rang : {{rang}}',
        fontFamily: 'Inter',
        fontSize: 15,
        fontWeight: 'bold',
        color: '#1e1b4b',
        textAlign: 'center'
      },

      // Date and Place
      {
        id: 'el-date-place',
        type: 'text',
        x: 561.5,
        y: 555,
        width: 800,
        height: 30,
        content: 'Fait sous le Sceau de l\'Établissement à Paris, le {{date_obtention}}',
        fontFamily: 'Playfair Display',
        fontSize: 14,
        fontStyle: 'italic',
        color: '#64748b',
        textAlign: 'center'
      },

      // Center Official Stamp Ornament
      {
        id: 'el-center-seal',
        type: 'text',
        x: 561.5,
        y: 630,
        width: 300,
        height: 35,
        content: '★ SCEAU OFFICIEL D\'EXCELLENCE ★',
        fontFamily: 'Outfit',
        fontSize: 11,
        fontWeight: 'bold',
        color: '#d97706',
        textAlign: 'center'
      },

      // Signatures Left Column
      {
        id: 'el-sig-left-title',
        type: 'text',
        x: 240,
        y: 620,
        width: 300,
        height: 25,
        content: 'La Responsable Pédagogique',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#1e1b4b',
        textAlign: 'center'
      },
      {
        id: 'el-sig-left-name',
        type: 'text',
        x: 240,
        y: 685,
        width: 300,
        height: 25,
        content: 'Dr. Hélène ROUSSEAU',
        fontFamily: 'Playfair Display',
        fontSize: 13,
        color: '#475569',
        textAlign: 'center'
      },

      // Signatures Right Column
      {
        id: 'el-sig-right-title',
        type: 'text',
        x: 880,
        y: 620,
        width: 300,
        height: 25,
        content: 'Le Directeur de l\'Établissement',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#1e1b4b',
        textAlign: 'center'
      },
      {
        id: 'el-sig-right-name',
        type: 'text',
        x: 880,
        y: 685,
        width: 300,
        height: 25,
        content: 'Prof. Alexandre DE VANCE',
        fontFamily: 'Playfair Display',
        fontSize: 13,
        color: '#475569',
        textAlign: 'center'
      },

      // Numbering Footer
      {
        id: 'el-numbering',
        type: 'text',
        x: 70,
        y: 720,
        width: 350,
        height: 25,
        content: 'N° d\'enregistrement : {{numero}}',
        fontFamily: 'Inter',
        fontSize: 10,
        color: '#94a3b8',
        textAlign: 'left'
      }
    ]
  },
  {
    id: 'tmpl-modern-tech',
    name: 'Certificat Moderne Épuré Cyan',
    description: 'Style contemporain minimaliste avec des aplats cyan/indigo et typographie épurée centrée',
    category: 'certificat',
    pageSize: 'A4',
    orientation: 'landscape',
    dimensions: { width: 1123, height: 794 },
    themeColor: '#0284c7',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    elements: [
      {
        id: 'el-bg-bar',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 25,
        height: 794,
        backgroundColor: '#0284c7',
        isLocked: true
      },
      {
        id: 'el-header-title',
        type: 'text',
        x: 561.5,
        y: 85,
        width: 850,
        height: 50,
        content: 'CERTIFICAT DE COMPÉTENCE PROFESSIONNELLE',
        fontFamily: 'Outfit',
        fontSize: 34,
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'center'
      },
      {
        id: 'el-sub-header',
        type: 'text',
        x: 561.5,
        y: 140,
        width: 800,
        height: 30,
        content: 'DÉCERNÉ PAR L\'INSTITUT SUPÉRIEUR DES HAUTES ÉTUDES & TECHNOLOGIES',
        fontFamily: 'Inter',
        fontSize: 11,
        fontWeight: '600',
        color: '#0284c7',
        textAlign: 'center'
      },
      {
        id: 'el-cert-text-1',
        type: 'text',
        x: 561.5,
        y: 230,
        width: 800,
        height: 30,
        content: 'Il est officiellement certifié que :',
        fontFamily: 'Playfair Display',
        fontSize: 16,
        fontStyle: 'italic',
        color: '#64748b',
        textAlign: 'center'
      },
      {
        id: 'el-name',
        type: 'variable',
        variableName: '{{nom_complet}}',
        x: 561.5,
        y: 285,
        width: 900,
        height: 50,
        content: '{{nom_complet}}',
        fontFamily: 'Outfit',
        fontSize: 36,
        fontWeight: 'bold',
        color: '#0369a1',
        textAlign: 'center'
      },
      {
        id: 'el-desc',
        type: 'text',
        x: 561.5,
        y: 370,
        width: 880,
        height: 70,
        content: 'a validé avec succès l\'intégralité des modules et des épreuves pratiques pour le cursus\n{{formation}}\n(Spécialité : {{specialite}})',
        fontFamily: 'Inter',
        fontSize: 16,
        color: '#334155',
        textAlign: 'center'
      },
      {
        id: 'el-meta',
        type: 'text',
        x: 561.5,
        y: 480,
        width: 800,
        height: 30,
        content: 'Session : {{annee_academique}}   •   Volume : {{duree}}   •   Mention : {{mention}}',
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'center'
      },
      {
        id: 'el-date',
        type: 'text',
        x: 561.5,
        y: 560,
        width: 600,
        height: 30,
        content: 'Fait sous le Sceau Officiel le {{date_obtention}}   •   N° : {{numero}}',
        fontFamily: 'Inter',
        fontSize: 12,
        color: '#64748b',
        textAlign: 'center'
      },
      {
        id: 'el-sig-resp',
        type: 'text',
        x: 250,
        y: 640,
        width: 300,
        height: 30,
        content: 'La Responsable Pédagogique\nDr. Hélène ROUSSEAU',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: '600',
        color: '#334155',
        textAlign: 'center'
      },
      {
        id: 'el-sig-director',
        type: 'text',
        x: 870,
        y: 640,
        width: 300,
        height: 30,
        content: 'Le Directeur Général\nProf. Alexandre DE VANCE',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: '600',
        color: '#334155',
        textAlign: 'center'
      }
    ]
  },

  // 3. DIPLÔME D'HONNEUR & MÉRITE — ÉMERAUDE & OR IMPÉRIAL
  {
    id: 'tmpl-diplome-emerald-honor',
    name: 'Diplôme d\'Excellence Émeraude & Or Impérial',
    description: 'Style académique royal prestigieux à quadruple cadre or et vert émeraude pour les diplômes majeurs',
    category: 'diplome',
    pageSize: 'A4',
    orientation: 'landscape',
    dimensions: { width: 1123, height: 794 },
    themeColor: '#059669',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    elements: [
      {
        id: 'el-em-border-1',
        type: 'rectangle',
        x: 24,
        y: 24,
        width: 1075,
        height: 746,
        backgroundColor: 'transparent',
        borderColor: '#064e3b',
        borderWidth: 4,
        isLocked: true
      },
      {
        id: 'el-em-border-2',
        type: 'rectangle',
        x: 34,
        y: 34,
        width: 1055,
        height: 726,
        backgroundColor: 'transparent',
        borderColor: '#d97706',
        borderWidth: 2,
        isLocked: true
      },
      {
        id: 'el-em-header-seal',
        type: 'text',
        x: 561.5,
        y: 60,
        width: 800,
        height: 30,
        content: '⚜   ACADÉMIE DES HAUTES ÉTUDES & DE L\'INNOVATION   ⚜',
        fontFamily: 'Outfit',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#d97706',
        textAlign: 'center'
      },
      {
        id: 'el-em-inst-name',
        type: 'text',
        x: 561.5,
        y: 95,
        width: 950,
        height: 35,
        content: 'INSTITUT SUPÉRIEUR DES HAUTES ÉTUDES & TECHNOLOGIES',
        fontFamily: 'Cinzel',
        fontSize: 20,
        fontWeight: 'bold',
        color: '#064e3b',
        textAlign: 'center'
      },
      {
        id: 'el-em-title',
        type: 'text',
        x: 561.5,
        y: 165,
        width: 900,
        height: 60,
        content: 'DIPLÔME D\'HONNEUR & DE MÉRITE',
        fontFamily: 'Outfit',
        fontSize: 40,
        fontWeight: 'bold',
        color: '#047857',
        textAlign: 'center'
      },
      {
        id: 'el-em-sep',
        type: 'text',
        x: 561.5,
        y: 225,
        width: 500,
        height: 25,
        content: '✦   ━━━━━━━━━━   ★   ━━━━━━━━━━   ✦',
        fontFamily: 'Inter',
        fontSize: 13,
        color: '#d97706',
        textAlign: 'center'
      },
      {
        id: 'el-em-intro',
        type: 'text',
        x: 561.5,
        y: 265,
        width: 900,
        height: 30,
        content: 'Le Conseil d\'Administration et le Grand Jury Académique confèrent le présent titre à :',
        fontFamily: 'Playfair Display',
        fontSize: 16,
        fontStyle: 'italic',
        color: '#475569',
        textAlign: 'center'
      },
      {
        id: 'el-em-name',
        type: 'variable',
        variableName: '{{nom_complet}}',
        x: 561.5,
        y: 320,
        width: 950,
        height: 55,
        content: '{{nom_complet}}',
        fontFamily: 'Cinzel',
        fontSize: 36,
        fontWeight: 'bold',
        color: '#064e3b',
        textAlign: 'center'
      },
      {
        id: 'el-em-text',
        type: 'text',
        x: 561.5,
        y: 395,
        width: 900,
        height: 70,
        content: 'En reconnaissance de ses résultats exceptionnels et de sa maîtrise remarquable dans le cursus\n{{formation}}\n(Spécialité : {{specialite}})',
        fontFamily: 'Inter',
        fontSize: 16,
        color: '#1f2937',
        textAlign: 'center'
      },
      {
        id: 'el-em-pill',
        type: 'text',
        x: 561.5,
        y: 485,
        width: 850,
        height: 35,
        content: '★ Mention : {{mention}}    •    Moyenne : {{moyenne}}    •    Rang : {{rang}} ★',
        fontFamily: 'Inter',
        fontSize: 15,
        fontWeight: 'bold',
        color: '#047857',
        textAlign: 'center'
      },
      {
        id: 'el-em-date',
        type: 'text',
        x: 561.5,
        y: 550,
        width: 800,
        height: 25,
        content: 'Fait avec solennité à Paris, le {{date_obtention}}   •   Enregistré sous le N° : {{numero}}',
        fontFamily: 'Playfair Display',
        fontSize: 13,
        fontStyle: 'italic',
        color: '#64748b',
        textAlign: 'center'
      },
      {
        id: 'el-em-sig-left',
        type: 'text',
        x: 250,
        y: 630,
        width: 320,
        height: 50,
        content: 'Le Président du Jury d\'Examen\nDr. Hélène ROUSSEAU',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#064e3b',
        textAlign: 'center'
      },
      {
        id: 'el-em-sig-right',
        type: 'text',
        x: 870,
        y: 630,
        width: 320,
        height: 50,
        content: 'Le Recteur de l\'Établissement\nProf. Alexandre DE VANCE',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#064e3b',
        textAlign: 'center'
      }
    ]
  },

  // 4. CERTIFICAT DE STAGE & IMMERSION PROFESSIONNELLE
  {
    id: 'tmpl-stage-professional',
    name: 'Certificat de Stage & Immersion Entreprise Saphir',
    description: 'Modèle élégant dédié aux attestations de stage d\'immersion et de fin d\'études en entreprise',
    category: 'stage',
    pageSize: 'A4',
    orientation: 'landscape',
    dimensions: { width: 1123, height: 794 },
    themeColor: '#2563eb',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    elements: [
      {
        id: 'el-stg-bar-top',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 1123,
        height: 12,
        backgroundColor: '#2563eb',
        isLocked: true
      },
      {
        id: 'el-stg-border',
        type: 'rectangle',
        x: 30,
        y: 30,
        width: 1063,
        height: 734,
        backgroundColor: 'transparent',
        borderColor: '#cbd5e1',
        borderWidth: 2,
        isLocked: true
      },
      {
        id: 'el-stg-header',
        type: 'text',
        x: 561.5,
        y: 70,
        width: 800,
        height: 25,
        content: 'PROGRAMME D\'IMMERSION & DE PERFECTIONNEMENT EN ENTREPRISE',
        fontFamily: 'Outfit',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#2563eb',
        textAlign: 'center'
      },
      {
        id: 'el-stg-title',
        type: 'text',
        x: 561.5,
        y: 120,
        width: 900,
        height: 55,
        content: 'CERTIFICAT DE STAGE PROFESSIONNEL',
        fontFamily: 'Outfit',
        fontSize: 38,
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'center'
      },
      {
        id: 'el-stg-sub',
        type: 'text',
        x: 561.5,
        y: 185,
        width: 800,
        height: 25,
        content: 'Attestation officielle de validation de stage pratique de fin d\'études',
        fontFamily: 'Inter',
        fontSize: 13,
        color: '#64748b',
        textAlign: 'center'
      },
      {
        id: 'el-stg-body-1',
        type: 'text',
        x: 561.5,
        y: 255,
        width: 850,
        height: 30,
        content: 'La Direction des Ressources Humaines certifie par la présente que :',
        fontFamily: 'Playfair Display',
        fontSize: 16,
        fontStyle: 'italic',
        color: '#334155',
        textAlign: 'center'
      },
      {
        id: 'el-stg-name',
        type: 'variable',
        variableName: '{{nom_complet}}',
        x: 561.5,
        y: 305,
        width: 900,
        height: 50,
        content: '{{nom_complet}}',
        fontFamily: 'Outfit',
        fontSize: 34,
        fontWeight: 'bold',
        color: '#1d4ed8',
        textAlign: 'center'
      },
      {
        id: 'el-stg-body-2',
        type: 'text',
        x: 561.5,
        y: 380,
        width: 900,
        height: 75,
        content: 'a effectué avec assiduité et grand professionnalisme son stage d\'application pratique\nen qualité de {{specialite}} dans le cadre de sa formation en\n{{formation}}.',
        fontFamily: 'Inter',
        fontSize: 16,
        color: '#334155',
        textAlign: 'center'
      },
      {
        id: 'el-stg-pill',
        type: 'text',
        x: 561.5,
        y: 485,
        width: 850,
        height: 35,
        content: 'Durée : {{duree}}   •   Évaluation : {{mention}}   •   Note d\'entreprise : {{moyenne}}',
        fontFamily: 'Inter',
        fontSize: 15,
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'center'
      },
      {
        id: 'el-stg-date',
        type: 'text',
        x: 561.5,
        y: 555,
        width: 800,
        height: 25,
        content: 'Fait et délivré pour servir et valoir ce que de droit, le {{date_obtention}}',
        fontFamily: 'Inter',
        fontSize: 12,
        color: '#64748b',
        textAlign: 'center'
      },
      {
        id: 'el-stg-sig-1',
        type: 'text',
        x: 250,
        y: 635,
        width: 300,
        height: 50,
        content: 'Le Tuteur de Stage Professionnel\nIng. Marc TCHIENTCHEU',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#1e293b',
        textAlign: 'center'
      },
      {
        id: 'el-stg-sig-2',
        type: 'text',
        x: 870,
        y: 635,
        width: 300,
        height: 50,
        content: 'La Direction des Ressources Humaines\nDr. Hélène ROUSSEAU',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#1e293b',
        textAlign: 'center'
      }
    ]
  },

  // 5. CERTIFICAT CYBERSÉCURITÉ & CLOUD
  {
    id: 'tmpl-cyber-security',
    name: 'Certificat International Cybersécurité & Cloud',
    description: 'Design haute technologie cyan et bleu nuit avec badge de certification accréditée',
    category: 'certificat',
    pageSize: 'A4',
    orientation: 'landscape',
    dimensions: { width: 1123, height: 794 },
    themeColor: '#06b6d4',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    elements: [
      {
        id: 'el-cyb-border-1',
        type: 'rectangle',
        x: 25,
        y: 25,
        width: 1073,
        height: 744,
        backgroundColor: 'transparent',
        borderColor: '#0f172a',
        borderWidth: 4,
        isLocked: true
      },
      {
        id: 'el-cyb-border-2',
        type: 'rectangle',
        x: 35,
        y: 35,
        width: 1053,
        height: 724,
        backgroundColor: 'transparent',
        borderColor: '#06b6d4',
        borderWidth: 2,
        isLocked: true
      },
      {
        id: 'el-cyb-badge',
        type: 'text',
        x: 561.5,
        y: 65,
        width: 800,
        height: 25,
        content: '🛡️  INTERNATIONAL CYBERSECURITY & CLOUD ACCREDITATION  🛡️',
        fontFamily: 'Outfit',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#0891b2',
        textAlign: 'center'
      },
      {
        id: 'el-cyb-inst',
        type: 'text',
        x: 561.5,
        y: 100,
        width: 900,
        height: 35,
        content: 'INSTITUTE OF ADVANCED SECURITY & CLOUD ARCHITECTURE',
        fontFamily: 'Cinzel',
        fontSize: 18,
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'center'
      },
      {
        id: 'el-cyb-title',
        type: 'text',
        x: 561.5,
        y: 165,
        width: 900,
        height: 55,
        content: 'EXPERT CYBERSECURITY CERTIFICATION',
        fontFamily: 'Outfit',
        fontSize: 38,
        fontWeight: 'bold',
        color: '#0284c7',
        textAlign: 'center'
      },
      {
        id: 'el-cyb-intro',
        type: 'text',
        x: 561.5,
        y: 245,
        width: 850,
        height: 30,
        content: 'This official credential certifies that :',
        fontFamily: 'Playfair Display',
        fontSize: 16,
        fontStyle: 'italic',
        color: '#64748b',
        textAlign: 'center'
      },
      {
        id: 'el-cyb-name',
        type: 'variable',
        variableName: '{{nom_complet}}',
        x: 561.5,
        y: 295,
        width: 900,
        height: 50,
        content: '{{nom_complet}}',
        fontFamily: 'Outfit',
        fontSize: 36,
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'center'
      },
      {
        id: 'el-cyb-body',
        type: 'text',
        x: 561.5,
        y: 370,
        width: 900,
        height: 75,
        content: 'has successfully demonstrated comprehensive mastery in Cloud Infrastructure Defense, Ethical Hacking & Risk Mitigation\nProgramme : {{formation}} (Specialization: {{specialite}})',
        fontFamily: 'Inter',
        fontSize: 15,
        color: '#334155',
        textAlign: 'center'
      },
      {
        id: 'el-cyb-meta',
        type: 'text',
        x: 561.5,
        y: 475,
        width: 850,
        height: 35,
        content: 'Grade : {{mention}}   •   Score : {{moyenne}}   •   Duration : {{duree}}',
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 'bold',
        color: '#0284c7',
        textAlign: 'center'
      },
      {
        id: 'el-cyb-hash',
        type: 'text',
        x: 561.5,
        y: 545,
        width: 800,
        height: 25,
        content: 'Security Token : SEC-{{matricule}}-2026-OK   •   Issued on : {{date_obtention}}',
        fontFamily: 'Inter',
        fontSize: 11,
        color: '#94a3b8',
        textAlign: 'center'
      },
      {
        id: 'el-cyb-sig-1',
        type: 'text',
        x: 250,
        y: 625,
        width: 300,
        height: 50,
        content: 'Chief Information Security Officer\nDr. Alex ROUSSEAU',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'center'
      },
      {
        id: 'el-cyb-sig-2',
        type: 'text',
        x: 870,
        y: 625,
        width: 300,
        height: 50,
        content: 'Dean of Computing\nProf. Alexandre DE VANCE',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#0f172a',
        textAlign: 'center'
      }
    ]
  },

  // 6. ATTESTATION FORMATION CONTINUE — RUBIS & OR
  {
    id: 'tmpl-formation-rubis-gold',
    name: 'Attestation de Formation Continue Rubis & Or',
    description: 'Couleurs bordeaux et dorure chaude avec typographie élégante pour formations pour adultes',
    category: 'attestation',
    pageSize: 'A4',
    orientation: 'landscape',
    dimensions: { width: 1123, height: 794 },
    themeColor: '#881337',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    elements: [
      {
        id: 'el-rb-border-1',
        type: 'rectangle',
        x: 25,
        y: 25,
        width: 1073,
        height: 744,
        backgroundColor: 'transparent',
        borderColor: '#881337',
        borderWidth: 4,
        isLocked: true
      },
      {
        id: 'el-rb-border-2',
        type: 'rectangle',
        x: 35,
        y: 35,
        width: 1053,
        height: 724,
        backgroundColor: 'transparent',
        borderColor: '#d97706',
        borderWidth: 1.5,
        isLocked: true
      },
      {
        id: 'el-rb-top',
        type: 'text',
        x: 561.5,
        y: 65,
        width: 800,
        height: 25,
        content: '✦  FORMATION CONTINUE & DÉVELOPPEMENT DES CADRES  ✦',
        fontFamily: 'Outfit',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#b45309',
        textAlign: 'center'
      },
      {
        id: 'el-rb-inst',
        type: 'text',
        x: 561.5,
        y: 100,
        width: 900,
        height: 35,
        content: 'INSTITUT SUPÉRIEUR DES HAUTES ÉTUDES & TECHNOLOGIES',
        fontFamily: 'Cinzel',
        fontSize: 20,
        fontWeight: 'bold',
        color: '#881337',
        textAlign: 'center'
      },
      {
        id: 'el-rb-title',
        type: 'text',
        x: 561.5,
        y: 165,
        width: 900,
        height: 55,
        content: 'ATTESTATION DE FORMATION CONTINUE',
        fontFamily: 'Outfit',
        fontSize: 36,
        fontWeight: 'bold',
        color: '#9f1239',
        textAlign: 'center'
      },
      {
        id: 'el-rb-intro',
        type: 'text',
        x: 561.5,
        y: 245,
        width: 850,
        height: 30,
        content: 'La Direction de la Formation Continue atteste que :',
        fontFamily: 'Playfair Display',
        fontSize: 16,
        fontStyle: 'italic',
        color: '#475569',
        textAlign: 'center'
      },
      {
        id: 'el-rb-name',
        type: 'variable',
        variableName: '{{nom_complet}}',
        x: 561.5,
        y: 295,
        width: 900,
        height: 55,
        content: '{{nom_complet}}',
        fontFamily: 'Playfair Display',
        fontSize: 36,
        fontWeight: 'bold',
        color: '#881337',
        textAlign: 'center'
      },
      {
        id: 'el-rb-body',
        type: 'text',
        x: 561.5,
        y: 375,
        width: 900,
        height: 75,
        content: 'a suivi avec régularité et validé avec succès l\'ensemble des épreuves d\'évaluation du cycle certifiant :\n{{formation}}\n(Spécialisation professionnelle : {{specialite}})',
        fontFamily: 'Inter',
        fontSize: 16,
        color: '#334155',
        textAlign: 'center'
      },
      {
        id: 'el-rb-pill',
        type: 'text',
        x: 561.5,
        y: 480,
        width: 850,
        height: 35,
        content: 'Session : {{annee_academique}}   •   Volume Horaire : {{duree}}   •   Mention : {{mention}}',
        fontFamily: 'Inter',
        fontSize: 15,
        fontWeight: 'bold',
        color: '#881337',
        textAlign: 'center'
      },
      {
        id: 'el-rb-date',
        type: 'text',
        x: 561.5,
        y: 550,
        width: 800,
        height: 25,
        content: 'Délivré à Paris, le {{date_obtention}}   •   Réf : {{numero}}',
        fontFamily: 'Inter',
        fontSize: 12,
        color: '#64748b',
        textAlign: 'center'
      },
      {
        id: 'el-rb-sig-1',
        type: 'text',
        x: 250,
        y: 630,
        width: 300,
        height: 50,
        content: 'La Responsable Pédagogique\nDr. Hélène ROUSSEAU',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#881337',
        textAlign: 'center'
      },
      {
        id: 'el-rb-sig-2',
        type: 'text',
        x: 870,
        y: 630,
        width: 300,
        height: 50,
        content: 'Le Directeur de la Formation\nProf. Alexandre DE VANCE',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#881337',
        textAlign: 'center'
      }
    ]
  },

  // 7. PRIX D'INNOVATION & PARTICIPATION HACKATHON
  {
    id: 'tmpl-hackathon-innovation',
    name: 'Attestation & Prix Hackathon Violet & Ambre',
    description: 'Style dynamique moderne pour concours technologiques, challenges et hackathons',
    category: 'participation',
    pageSize: 'A4',
    orientation: 'landscape',
    dimensions: { width: 1123, height: 794 },
    themeColor: '#7c3aed',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    elements: [
      {
        id: 'el-hk-top-bar',
        type: 'rectangle',
        x: 0,
        y: 0,
        width: 1123,
        height: 14,
        backgroundColor: '#7c3aed',
        isLocked: true
      },
      {
        id: 'el-hk-border',
        type: 'rectangle',
        x: 28,
        y: 28,
        width: 1067,
        height: 738,
        backgroundColor: 'transparent',
        borderColor: '#e2e8f0',
        borderWidth: 2,
        isLocked: true
      },
      {
        id: 'el-hk-badge',
        type: 'text',
        x: 561.5,
        y: 65,
        width: 800,
        height: 25,
        content: '⚡  INTERNATIONAL TECH & AI INNOVATION CHALLENGE  ⚡',
        fontFamily: 'Outfit',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#7c3aed',
        textAlign: 'center'
      },
      {
        id: 'el-hk-title',
        type: 'text',
        x: 561.5,
        y: 115,
        width: 900,
        height: 60,
        content: 'PRIX D\'INNOVATION & D\'EXCELLENCE',
        fontFamily: 'Outfit',
        fontSize: 40,
        fontWeight: 'bold',
        color: '#1e1b4b',
        textAlign: 'center'
      },
      {
        id: 'el-hk-intro',
        type: 'text',
        x: 561.5,
        y: 195,
        width: 850,
        height: 30,
        content: 'Le Comité d\'Organisation et le Jury d\'Experts décernent cette distinction à :',
        fontFamily: 'Playfair Display',
        fontSize: 16,
        fontStyle: 'italic',
        color: '#64748b',
        textAlign: 'center'
      },
      {
        id: 'el-hk-name',
        type: 'variable',
        variableName: '{{nom_complet}}',
        x: 561.5,
        y: 255,
        width: 900,
        height: 55,
        content: '{{nom_complet}}',
        fontFamily: 'Outfit',
        fontSize: 38,
        fontWeight: 'bold',
        color: '#6d28d9',
        textAlign: 'center'
      },
      {
        id: 'el-hk-body',
        type: 'text',
        x: 561.5,
        y: 345,
        width: 900,
        height: 75,
        content: 'Pour la conception et la réalisation du projet innovant dans la catégorie\n{{formation}}\n(Spécialisation : {{specialite}})',
        fontFamily: 'Inter',
        fontSize: 16,
        color: '#334155',
        textAlign: 'center'
      },
      {
        id: 'el-hk-pill',
        type: 'text',
        x: 561.5,
        y: 450,
        width: 850,
        height: 35,
        content: '🏆 Distinction : {{mention}}   •   Classement : {{rang}}   •   Note du Jury : {{moyenne}}',
        fontFamily: 'Inter',
        fontSize: 15,
        fontWeight: 'bold',
        color: '#ea580c',
        textAlign: 'center'
      },
      {
        id: 'el-hk-date',
        type: 'text',
        x: 561.5,
        y: 535,
        width: 800,
        height: 25,
        content: 'Fait le {{date_obtention}}   •   Certificat ID : {{numero}}',
        fontFamily: 'Inter',
        fontSize: 12,
        color: '#94a3b8',
        textAlign: 'center'
      },
      {
        id: 'el-hk-sig-1',
        type: 'text',
        x: 250,
        y: 620,
        width: 300,
        height: 50,
        content: 'Le Président du Jury Innovation\nDr. Thomas VIAL',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#1e1b4b',
        textAlign: 'center'
      },
      {
        id: 'el-hk-sig-2',
        type: 'text',
        x: 870,
        y: 620,
        width: 300,
        height: 50,
        content: 'Le Directeur du Hackathon\nProf. Alexandre DE VANCE',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#1e1b4b',
        textAlign: 'center'
      }
    ]
  },

  // 8. DIPLÔME DE MASTÈRE PROFESSIONNEL — PLATINE & NOIR ONYX
  {
    id: 'tmpl-master-platinum',
    name: 'Diplôme de Mastère Platine & Noir Onyx',
    description: 'Style suisse et allemand minimaliste de très haute distinction pour grades universitaires',
    category: 'diplome',
    pageSize: 'A4',
    orientation: 'landscape',
    dimensions: { width: 1123, height: 794 },
    themeColor: '#18181b',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    elements: [
      {
        id: 'el-plt-border',
        type: 'rectangle',
        x: 35,
        y: 35,
        width: 1053,
        height: 724,
        backgroundColor: 'transparent',
        borderColor: '#18181b',
        borderWidth: 2,
        isLocked: true
      },
      {
        id: 'el-plt-border-in',
        type: 'rectangle',
        x: 45,
        y: 45,
        width: 1033,
        height: 704,
        backgroundColor: 'transparent',
        borderColor: '#a1a1aa',
        borderWidth: 1,
        isLocked: true
      },
      {
        id: 'el-plt-top',
        type: 'text',
        x: 561.5,
        y: 80,
        width: 800,
        height: 25,
        content: 'MINISTÈRE DE L\'ENSEIGNEMENT SUPÉRIEUR ET DE LA RECHERCHE',
        fontFamily: 'Outfit',
        fontSize: 11,
        fontWeight: 'bold',
        color: '#71717a',
        textAlign: 'center'
      },
      {
        id: 'el-plt-inst',
        type: 'text',
        x: 561.5,
        y: 115,
        width: 900,
        height: 35,
        content: 'INSTITUT SUPÉRIEUR DES HAUTES ÉTUDES & TECHNOLOGIES',
        fontFamily: 'Cinzel',
        fontSize: 22,
        fontWeight: 'bold',
        color: '#18181b',
        textAlign: 'center'
      },
      {
        id: 'el-plt-title',
        type: 'text',
        x: 561.5,
        y: 180,
        width: 900,
        height: 55,
        content: 'DIPLÔME DE MASTÈRE PROFESSIONNEL',
        fontFamily: 'Cinzel',
        fontSize: 34,
        fontWeight: 'bold',
        color: '#18181b',
        textAlign: 'center'
      },
      {
        id: 'el-plt-intro',
        type: 'text',
        x: 561.5,
        y: 260,
        width: 850,
        height: 30,
        content: 'Vu le procès-verbal du Jury d\'Examen, le grade de Mastère est conféré à :',
        fontFamily: 'Playfair Display',
        fontSize: 16,
        fontStyle: 'italic',
        color: '#52525b',
        textAlign: 'center'
      },
      {
        id: 'el-plt-name',
        type: 'variable',
        variableName: '{{nom_complet}}',
        x: 561.5,
        y: 310,
        width: 900,
        height: 50,
        content: '{{nom_complet}}',
        fontFamily: 'Outfit',
        fontSize: 36,
        fontWeight: 'bold',
        color: '#18181b',
        textAlign: 'center'
      },
      {
        id: 'el-plt-body',
        type: 'text',
        x: 561.5,
        y: 385,
        width: 900,
        height: 75,
        content: 'Pour le programme d\'études supérieures spécialisées en\n{{formation}}\n(Spécialité : {{specialite}})',
        fontFamily: 'Inter',
        fontSize: 16,
        color: '#27272a',
        textAlign: 'center'
      },
      {
        id: 'el-plt-meta',
        type: 'text',
        x: 561.5,
        y: 485,
        width: 850,
        height: 35,
        content: 'Mention : {{mention}}   •   Moyenne Générale : {{moyenne}}   •   Session : {{annee_academique}}',
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 'bold',
        color: '#18181b',
        textAlign: 'center'
      },
      {
        id: 'el-plt-date',
        type: 'text',
        x: 561.5,
        y: 550,
        width: 800,
        height: 25,
        content: 'Fait sous le Sceau de l\'État, le {{date_obtention}}   •   N° Matricule : {{matricule}}',
        fontFamily: 'Playfair Display',
        fontSize: 12,
        fontStyle: 'italic',
        color: '#71717a',
        textAlign: 'center'
      },
      {
        id: 'el-plt-sig-1',
        type: 'text',
        x: 250,
        y: 630,
        width: 300,
        height: 50,
        content: 'Le Président du Jury d\'Examen\nDr. Hélène ROUSSEAU',
        fontFamily: 'Cinzel',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#18181b',
        textAlign: 'center'
      },
      {
        id: 'el-plt-sig-2',
        type: 'text',
        x: 870,
        y: 630,
        width: 300,
        height: 50,
        content: 'Le Recteur de l\'Institut\nProf. Alexandre DE VANCE',
        fontFamily: 'Cinzel',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#18181b',
        textAlign: 'center'
      }
    ]
  },

  // 9. CERTIFICAT DATA SCIENCE & INTELLIGENCE ARTIFICIELLE
  {
    id: 'tmpl-data-ai-expert',
    name: 'Certificat Data Science & IA Bleu Nuit & Teal',
    description: 'Design haute fidélité pour les cursus Data Science, Machine Learning et IA générative',
    category: 'certificat',
    pageSize: 'A4',
    orientation: 'landscape',
    dimensions: { width: 1123, height: 794 },
    themeColor: '#0d9488',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    elements: [
      {
        id: 'el-ai-border',
        type: 'rectangle',
        x: 25,
        y: 25,
        width: 1073,
        height: 744,
        backgroundColor: 'transparent',
        borderColor: '#0f766e',
        borderWidth: 3,
        isLocked: true
      },
      {
        id: 'el-ai-top',
        type: 'text',
        x: 561.5,
        y: 65,
        width: 800,
        height: 25,
        content: '🤖  ADVANCED DATA SCIENCE & ARTIFICIAL INTELLIGENCE INSTITUTE  🤖',
        fontFamily: 'Outfit',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#0d9488',
        textAlign: 'center'
      },
      {
        id: 'el-ai-title',
        type: 'text',
        x: 561.5,
        y: 115,
        width: 900,
        height: 55,
        content: 'CERTIFICAT D\'EXPERTISE EN DATA & IA',
        fontFamily: 'Outfit',
        fontSize: 38,
        fontWeight: 'bold',
        color: '#134e4a',
        textAlign: 'center'
      },
      {
        id: 'el-ai-intro',
        type: 'text',
        x: 561.5,
        y: 190,
        width: 850,
        height: 30,
        content: 'Ce certificat atteste officiellement que :',
        fontFamily: 'Playfair Display',
        fontSize: 16,
        fontStyle: 'italic',
        color: '#475569',
        textAlign: 'center'
      },
      {
        id: 'el-ai-name',
        type: 'variable',
        variableName: '{{nom_complet}}',
        x: 561.5,
        y: 245,
        width: 900,
        height: 50,
        content: '{{nom_complet}}',
        fontFamily: 'Outfit',
        fontSize: 36,
        fontWeight: 'bold',
        color: '#0f766e',
        textAlign: 'center'
      },
      {
        id: 'el-ai-body',
        type: 'text',
        x: 561.5,
        y: 330,
        width: 900,
        height: 80,
        content: 'a validé avec mention d\'excellence l\'ensemble des compétences théoriques et pratiques en\n{{formation}}\n(Architecture Deep Learning, LLMs & Spécialité : {{specialite}})',
        fontFamily: 'Inter',
        fontSize: 16,
        color: '#334155',
        textAlign: 'center'
      },
      {
        id: 'el-ai-meta',
        type: 'text',
        x: 561.5,
        y: 445,
        width: 850,
        height: 35,
        content: 'Mention : {{mention}}   •   Note de Synthèse : {{moyenne}}   •   Rang : {{rang}}',
        fontFamily: 'Inter',
        fontSize: 15,
        fontWeight: 'bold',
        color: '#0f766e',
        textAlign: 'center'
      },
      {
        id: 'el-ai-date',
        type: 'text',
        x: 561.5,
        y: 525,
        width: 800,
        height: 25,
        content: 'Délivré le {{date_obtention}}   •   Identifiant de Certification : {{numero}}',
        fontFamily: 'Inter',
        fontSize: 12,
        color: '#64748b',
        textAlign: 'center'
      },
      {
        id: 'el-ai-sig-1',
        type: 'text',
        x: 250,
        y: 615,
        width: 300,
        height: 50,
        content: 'Lead AI Research Director\nDr. Youssef BENALI',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#134e4a',
        textAlign: 'center'
      },
      {
        id: 'el-ai-sig-2',
        type: 'text',
        x: 870,
        y: 615,
        width: 300,
        height: 50,
        content: 'Directeur Général de l\'Institut\nProf. Alexandre DE VANCE',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#134e4a',
        textAlign: 'center'
      }
    ]
  },

  // 10. ATTESTATION D'ASSIDUITÉ & RÉUSSITE PÉDAGOGIQUE — VERT FORÊT
  {
    id: 'tmpl-assiduite-forest',
    name: 'Attestation d\'Assiduité & Réussite Vert Forêt & Or',
    description: 'Modèle officiel d\'assiduité de présence et de complétion de formation professionnelle',
    category: 'attestation',
    pageSize: 'A4',
    orientation: 'landscape',
    dimensions: { width: 1123, height: 794 },
    themeColor: '#15803d',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    elements: [
      {
        id: 'el-asd-border-1',
        type: 'rectangle',
        x: 25,
        y: 25,
        width: 1073,
        height: 744,
        backgroundColor: 'transparent',
        borderColor: '#14532d',
        borderWidth: 3.5,
        isLocked: true
      },
      {
        id: 'el-asd-border-2',
        type: 'rectangle',
        x: 35,
        y: 35,
        width: 1053,
        height: 724,
        backgroundColor: 'transparent',
        borderColor: '#ca8a04',
        borderWidth: 1.5,
        isLocked: true
      },
      {
        id: 'el-asd-top',
        type: 'text',
        x: 561.5,
        y: 65,
        width: 800,
        height: 25,
        content: 'ÉTABLISSEMENT D\'ENSEIGNEMENT ET DE FORMATION PROFESSIONNELLE',
        fontFamily: 'Outfit',
        fontSize: 11,
        fontWeight: 'bold',
        color: '#b45309',
        textAlign: 'center'
      },
      {
        id: 'el-asd-inst',
        type: 'text',
        x: 561.5,
        y: 95,
        width: 900,
        height: 35,
        content: 'INSTITUT SUPÉRIEUR DES HAUTES ÉTUDES & TECHNOLOGIES',
        fontFamily: 'Cinzel',
        fontSize: 20,
        fontWeight: 'bold',
        color: '#14532d',
        textAlign: 'center'
      },
      {
        id: 'el-asd-title',
        type: 'text',
        x: 561.5,
        y: 160,
        width: 900,
        height: 55,
        content: 'ATTESTATION DE FIN DE FORMATION',
        fontFamily: 'Outfit',
        fontSize: 38,
        fontWeight: 'bold',
        color: '#15803d',
        textAlign: 'center'
      },
      {
        id: 'el-asd-intro',
        type: 'text',
        x: 561.5,
        y: 235,
        width: 850,
        height: 30,
        content: 'Il est certifié par la présente que l\'apprenant(e) :',
        fontFamily: 'Playfair Display',
        fontSize: 16,
        fontStyle: 'italic',
        color: '#475569',
        textAlign: 'center'
      },
      {
        id: 'el-asd-name',
        type: 'variable',
        variableName: '{{nom_complet}}',
        x: 561.5,
        y: 285,
        width: 900,
        height: 50,
        content: '{{nom_complet}}',
        fontFamily: 'Outfit',
        fontSize: 36,
        fontWeight: 'bold',
        color: '#14532d',
        textAlign: 'center'
      },
      {
        id: 'el-asd-body',
        type: 'text',
        x: 561.5,
        y: 360,
        width: 900,
        height: 80,
        content: 'a suivi avec ponctualité, rigueur et assiduité l\'intégralité des enseignements du cursus :\n{{formation}}\n(Matricule de l\'étudiant : {{matricule}})',
        fontFamily: 'Inter',
        fontSize: 16,
        color: '#334155',
        textAlign: 'center'
      },
      {
        id: 'el-asd-meta',
        type: 'text',
        x: 561.5,
        y: 470,
        width: 850,
        height: 35,
        content: 'Volume Réalisé : {{duree}}   •   Taux de Présence : 100%   •   Mention : {{mention}}',
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 'bold',
        color: '#14532d',
        textAlign: 'center'
      },
      {
        id: 'el-asd-date',
        type: 'text',
        x: 561.5,
        y: 540,
        width: 800,
        height: 25,
        content: 'Fait pour valoir ce que de droit, le {{date_obtention}}   •   N° : {{numero}}',
        fontFamily: 'Inter',
        fontSize: 12,
        color: '#64748b',
        textAlign: 'center'
      },
      {
        id: 'el-asd-sig-1',
        type: 'text',
        x: 250,
        y: 620,
        width: 300,
        height: 50,
        content: 'Le Responsable de Scolarité\nDr. Hélène ROUSSEAU',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#14532d',
        textAlign: 'center'
      },
      {
        id: 'el-asd-sig-2',
        type: 'text',
        x: 870,
        y: 620,
        width: 300,
        height: 50,
        content: 'Le Directeur des Études\nProf. Alexandre DE VANCE',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#14532d',
        textAlign: 'center'
      }
    ]
  },

  // 11. CERTIFICAT INTERNATIONAL DE LANGUES & COMMUNICATION
  {
    id: 'tmpl-langue-international',
    name: 'Certificat de Langues & Communication Bordeaux & Or',
    description: 'Modèle accrédité pour écoles de langues, centres de certification CECRL et communication',
    category: 'certificat',
    pageSize: 'A4',
    orientation: 'landscape',
    dimensions: { width: 1123, height: 794 },
    themeColor: '#701a75',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    elements: [
      {
        id: 'el-lng-border-1',
        type: 'rectangle',
        x: 25,
        y: 25,
        width: 1073,
        height: 744,
        backgroundColor: 'transparent',
        borderColor: '#701a75',
        borderWidth: 3,
        isLocked: true
      },
      {
        id: 'el-lng-border-2',
        type: 'rectangle',
        x: 35,
        y: 35,
        width: 1053,
        height: 724,
        backgroundColor: 'transparent',
        borderColor: '#d97706',
        borderWidth: 1.5,
        isLocked: true
      },
      {
        id: 'el-lng-top',
        type: 'text',
        x: 561.5,
        y: 65,
        width: 800,
        height: 25,
        content: '🌐  INTERNATIONAL LANGUAGE & COMMUNICATION PROFICIENCY  🌐',
        fontFamily: 'Outfit',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#a21caf',
        textAlign: 'center'
      },
      {
        id: 'el-lng-title',
        type: 'text',
        x: 561.5,
        y: 115,
        width: 900,
        height: 55,
        content: 'CERTIFICAT DE COMPÉTENCE LINGUISTIQUE',
        fontFamily: 'Outfit',
        fontSize: 36,
        fontWeight: 'bold',
        color: '#4a044e',
        textAlign: 'center'
      },
      {
        id: 'el-lng-intro',
        type: 'text',
        x: 561.5,
        y: 190,
        width: 850,
        height: 30,
        content: 'La Commission Internationale d\'Évaluation certifie que :',
        fontFamily: 'Playfair Display',
        fontSize: 16,
        fontStyle: 'italic',
        color: '#475569',
        textAlign: 'center'
      },
      {
        id: 'el-lng-name',
        type: 'variable',
        variableName: '{{nom_complet}}',
        x: 561.5,
        y: 245,
        width: 900,
        height: 50,
        content: '{{nom_complet}}',
        fontFamily: 'Outfit',
        fontSize: 36,
        fontWeight: 'bold',
        color: '#701a75',
        textAlign: 'center'
      },
      {
        id: 'el-lng-body',
        type: 'text',
        x: 561.5,
        y: 330,
        width: 900,
        height: 80,
        content: 'a passé avec succès l\'ensemble des épreuves orales et écrites du programme certifiant en\n{{formation}}\n(Spécialisation : {{specialite}})',
        fontFamily: 'Inter',
        fontSize: 16,
        color: '#334155',
        textAlign: 'center'
      },
      {
        id: 'el-lng-meta',
        type: 'text',
        x: 561.5,
        y: 445,
        width: 850,
        height: 35,
        content: 'Niveau CECRL Validé : C1 (Avancé Supérieur)   •   Score : {{moyenne}}   •   Mention : {{mention}}',
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 'bold',
        color: '#701a75',
        textAlign: 'center'
      },
      {
        id: 'el-lng-date',
        type: 'text',
        x: 561.5,
        y: 525,
        width: 800,
        height: 25,
        content: 'Délivré sous accréditation européenne le {{date_obtention}}   •   N° : {{numero}}',
        fontFamily: 'Inter',
        fontSize: 12,
        color: '#64748b',
        textAlign: 'center'
      },
      {
        id: 'el-lng-sig-1',
        type: 'text',
        x: 250,
        y: 615,
        width: 300,
        height: 50,
        content: 'La Directrice des Examens\nDr. Sarah O\'CONNOR',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#4a044e',
        textAlign: 'center'
      },
      {
        id: 'el-lng-sig-2',
        type: 'text',
        x: 870,
        y: 615,
        width: 300,
        height: 50,
        content: 'Le Président du Centre International\nProf. Alexandre DE VANCE',
        fontFamily: 'Inter',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#4a044e',
        textAlign: 'center'
      }
    ]
  },

  // 12. EXECUTIVE LEADERSHIP & MANAGEMENT DIPLOMA
  {
    id: 'tmpl-executive-leadership',
    name: 'Executive Leadership & Management Bleu Royal & Or',
    description: 'Modèle haute direction pour programmes Executive MBA, leadership stratégique et gouvernance',
    category: 'diplome',
    pageSize: 'A4',
    orientation: 'landscape',
    dimensions: { width: 1123, height: 794 },
    themeColor: '#1e3a8a',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    elements: [
      {
        id: 'el-exe-border-1',
        type: 'rectangle',
        x: 25,
        y: 25,
        width: 1073,
        height: 744,
        backgroundColor: 'transparent',
        borderColor: '#1e3a8a',
        borderWidth: 4,
        isLocked: true
      },
      {
        id: 'el-exe-border-2',
        type: 'rectangle',
        x: 35,
        y: 35,
        width: 1053,
        height: 724,
        backgroundColor: 'transparent',
        borderColor: '#eab308',
        borderWidth: 1.5,
        isLocked: true
      },
      {
        id: 'el-exe-top',
        type: 'text',
        x: 561.5,
        y: 65,
        width: 800,
        height: 25,
        content: '🏛️  EXECUTIVE BUSINESS SCHOOL & LEADERSHIP INSTITUTE  🏛️',
        fontFamily: 'Outfit',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#ca8a04',
        textAlign: 'center'
      },
      {
        id: 'el-exe-inst',
        type: 'text',
        x: 561.5,
        y: 95,
        width: 900,
        height: 35,
        content: 'INSTITUT SUPÉRIEUR DES HAUTES ÉTUDES & TECHNOLOGIES',
        fontFamily: 'Cinzel',
        fontSize: 20,
        fontWeight: 'bold',
        color: '#1e3a8a',
        textAlign: 'center'
      },
      {
        id: 'el-exe-title',
        type: 'text',
        x: 561.5,
        y: 160,
        width: 900,
        height: 55,
        content: 'EXECUTIVE LEADERSHIP DIPLOMA',
        fontFamily: 'Outfit',
        fontSize: 38,
        fontWeight: 'bold',
        color: '#1e40af',
        textAlign: 'center'
      },
      {
        id: 'el-exe-intro',
        type: 'text',
        x: 561.5,
        y: 235,
        width: 850,
        height: 30,
        content: 'Le Conseil d\'Administration et la Faculté Executive décernent ce titre d\'Excellence à :',
        fontFamily: 'Playfair Display',
        fontSize: 16,
        fontStyle: 'italic',
        color: '#475569',
        textAlign: 'center'
      },
      {
        id: 'el-exe-name',
        type: 'variable',
        variableName: '{{nom_complet}}',
        x: 561.5,
        y: 285,
        width: 900,
        height: 50,
        content: '{{nom_complet}}',
        fontFamily: 'Cinzel',
        fontSize: 36,
        fontWeight: 'bold',
        color: '#1e3a8a',
        textAlign: 'center'
      },
      {
        id: 'el-exe-body',
        type: 'text',
        x: 561.5,
        y: 360,
        width: 900,
        height: 80,
        content: 'Pour avoir complété avec distinction l\'intégralité du programme intensif de Gouvernance & Direction Stratégique\n{{formation}}\n(Spécialisation : {{specialite}})',
        fontFamily: 'Inter',
        fontSize: 16,
        color: '#334155',
        textAlign: 'center'
      },
      {
        id: 'el-exe-meta',
        type: 'text',
        x: 561.5,
        y: 470,
        width: 850,
        height: 35,
        content: 'Session : {{annee_academique}}   •   Mention : {{mention}}   •   Rang : {{rang}}',
        fontFamily: 'Inter',
        fontSize: 14,
        fontWeight: 'bold',
        color: '#1e3a8a',
        textAlign: 'center'
      },
      {
        id: 'el-exe-date',
        type: 'text',
        x: 561.5,
        y: 540,
        width: 800,
        height: 25,
        content: 'Fait sous le Sceau Académique à Paris, le {{date_obtention}}   •   Certificat N° : {{numero}}',
        fontFamily: 'Playfair Display',
        fontSize: 12,
        fontStyle: 'italic',
        color: '#64748b',
        textAlign: 'center'
      },
      {
        id: 'el-exe-sig-1',
        type: 'text',
        x: 250,
        y: 620,
        width: 300,
        height: 50,
        content: 'Le Doyen de l\'Executive MBA\nDr. Hélène ROUSSEAU',
        fontFamily: 'Cinzel',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#1e3a8a',
        textAlign: 'center'
      },
      {
        id: 'el-exe-sig-2',
        type: 'text',
        x: 870,
        y: 620,
        width: 300,
        height: 50,
        content: 'Le Président du Conseil de Gouvernance\nProf. Alexandre DE VANCE',
        fontFamily: 'Cinzel',
        fontSize: 12,
        fontWeight: 'bold',
        color: '#1e3a8a',
        textAlign: 'center'
      }
    ]
  }
];
